### ISSUE TITLE
Strange neighbor solicit after reboot

### ISSUE THREAD

**Issue by arurke** [cetic/6lbr#103]
Setup is 6lbr on BBB with cc2531/cc2538 usb SLIP, and 1 x cc2650 sensortag with bleeding edge contiki running 6lbr client only.

I let 6lbr and node go to a steady-state and then reboot the 6lbr. After booting, I see:
1. 6lbr transmitting DIOs, source fe80::212:4b00:413:396a
2. Node transmit DAO with old DODAG
3. 6lbr transmit Neighbor Solicitation with IPv6 address: Source ::0000 and destination fe80::1:ff13:396a. (note, two last octet same as himself)
4. 6lbr repeat transmission 3 times with ~10 sec intervals
5. Normal operation

It seems this is triggered by the DAO from the node, maybe he gets confused of the DODAG matching himself? I observed and reproduced it on 1.3.x, 95% sure I saw it on master as well.

Capture from sniffer. 6lbr is :212:4b00:413:396a, node is :0709
http://filebin.ca/2D9ibfbeoMz1/6lbrBootOneCC2650withCetic6lbrClient.pcapng

Level 10 log during boot:
https://gist.github.com/arurke/b46bd108ddebffbe9c6f

Regards,
Andreas U.
www.netwurke.com

**Comment by laurentderu** [comment]
Thanks for all the information ! The root cause is a bug in Contiki stack (see https://github.com/contiki-os/contiki/issues/1106 :sometime the received packet is forwarded when the uip buffer is not cleared).

I have a temporary workaround in the develop branch, I'll back port it to the 1.3.x maintenance branch.
