### ISSUE TITLE
why does 6lbr examples squat reserved addresses?

### ISSUE THREAD

**Issue by serdarkose** [cetic/6lbr#126]
I wonder why the default settings and examples use reserved IPv6 addresses, instead of RFC 4193 addresses?

**Comment by laurentderu** [comment]
It only for historical reason, the default subnets are the subnets used in Contiki examples. There is a ongoing discussion happening there also, see https://github.com/contiki-os/contiki/pull/712

Because of all the existing documentation and examples, I'm a bit reluctant to switch to 4193, but suggestion on how to do so are always welcome :)
