### ISSUE TITLE
6lbr can't ping neighbour, route via (null)

### ISSUE THREAD

**Issue by tussock-cam** [cetic/6lbr#262]
I've got a 6lbr running on a beaglebone and a single device connected to it. I can see the status packet being sent from the node every minute when using a sniffer. The node is running web-demo with contiki @ a38cfc8 on a custom platform with a CC1310 radio. Initially it worked great, but after about 2 hours 6lbr can't talk to the node, even though it continually receives the node's packets.

I'm not 100% sure on my 6lbr version, unfortunately, but we installed with a cetic-6lbr_1.4.0_armhf.deb with MD5 284f6b385048acf4d7135107d0d95212  .

In the sensors list its status frequently changes from OK to NR, and its route is often removed. When it gets added, its state is typically:

> fd00::212:4b00:d2d:c202/128 via (null) 7678 s

The device's last seen never really goes above 60 seconds, so the BR is receiving its pings. It's always in the neighbor list and marked as REACHABLE. However, if I try and ping the node, I get nothing back:

> root@beaglebone:~# ping6 -c 1 fd00::212:4b00:d2d:c202
> PING fd00::212:4b00:d2d:c202(fd00::212:4b00:d2d:c202) 56 data bytes
> 
> --- fd00::212:4b00:d2d:c202 ping statistics ---
> 1 packets transmitted, 0 received, 100% packet loss, time 0ms
> 

If I look at the sniffer, I don't see anything getting sent out. However, I do notice frequent ICMPv6 pings from the node to 6lbr, which get replies. Not sure what these are, but am guessing it's part of normal RPL traffic? I also see 6lbr's DIO broadcasts, so its radio is obviously working. 

Restarting the node doesn't fix it, and I haven't restarted 6lbr yet because I don't want to lose an opportunity to get some useful debugging done. Probably worth noting that web/coap also don't work when the ping doesn't. 

Traceroute shows that the packet gets sent to the radio, but that's about it.

> traceroute to fd00::212:4b00:d2d:c202 (fd00::212:4b00:d2d:c202), 30 hops max, 80 byte packets
>  1  fd00::212:4b00:a27:c7e4 (fd00::212:4b00:a27:c7e4)  3.973 ms  3.964 ms  3.977 ms
>  2  * * *
>  ...
> 30  * * *
> 

Any suggestions for narrowing down the cause? I've attached my seemingly uninteresting 6lbr.log and a pcap if you're interested, (`d2d:c202` is the node, `a27:c7e4` is the slip radio). 

[6lbr.log.txt](https://github.com/cetic/6lbr/files/829805/6lbr.log.txt)
[single-node-6lbr-cant-talk-to-node.zip](https://github.com/cetic/6lbr/files/829806/single-node-6lbr-cant-talk-to-node.zip)

**Comment by laurentderu** [comment]
The problem is that, for unknown reason, the neighbor entry for your node has been removed from the neighbor table of 6LBR, this is the (null) in the routing table. Because of that, the BR is no longer able to forward the packets towards your node as the next hop of the configured route does not exist anymore.

Now the root cause is not clear to me at all, and as you said, the 6lbr.log file does not show anything useful. To be able to analyse further, you should enable the traces in uip-ds6-nbr and maybe also in uip-ds6-route, rpl-dag and rpl-icmp6.
Note that 6LBR 1.4.x is still based on Contiki 3.0, on the other hand, 6LBR 1.5.x, the current develop branch, is based on the latest version of Contiki which contains updates and fixes related to the neighbor table management. It quite possible that you are observing a bug that is already solved, so before digging too much into the issue I would suggest to try with the latest version of the develop branch.

Btw, the ping you observe is in fact not related to RPL, it's a feature of the cc26xx-web-demo firmware which ping periodically its parent to get the current RSSI.

**Comment by tussock-cam** [comment]
I'll test the develop branch and see if the issue remains. Just tried it now and the webserver fails after responding to one query, so need to figure out what's going on there. 

Will let you know how it goes.

**Comment by tussock-cam** [comment]
So I've looked into this a bit today and saw it kind of happen again. This is against commit 744ad0cd1c0ee75136e09b11e8e7160208418683.

Soon after building the code, but before adding any debugging, I had the node connect, reliably ping 6lbr and be marked as NR. I couldn't tell why it had no route, but saw that it happened. It wasn't listed as `via (null)`, it just wasn't there. 

I then enabled printing in `uip-ds6-nbr.c`, `uip-ds6-route.c`, `rpl-icmp6.c` and `rpl.c` and tried to make it happen again. I couldn't get it to happen by itself, but if I removed the route via the web interface it'd remain as NR for about an hour, at which point I reset it. When the node rejoined it was given a route, so that obviously isn't the issue I noted before.

Anyway, looked through the code and saw that a route is only ever added when a node sends a DAO, which happens when it changes dag/parent. So if a route is removed for whatever reason, the node remains unreachable for quite a period of time, and as far as I can tell, it will have no idea. 

So... should a route be added when we receive data from a node? Or maybe a DAO requested? I'm not terribly familiar with RPL, so maybe this is a dumb suggestion, but it seems weird to be able to receive from a node for so long without giving it a route, and without it knowing it doesn't have a route.

I'm going to reset the test and leave it running overnight to see if I can get the other issue to happen again.

**Comment by laurentderu** [comment]
In a RPL network, a downward route is only created when a valid DAO message is received. If a data packet is received from a node, a route is not created, otherwise you could have several downward routes towards the same node, some of them even not working as the radio conditions have changed.

In Contiki, the route created by RPL are protected, meaning that a route (and the corresponding next hop) will only be removed when an explicit No Path DAO (remove route message) or if the route lifetime has expired, or if there is a global or local repair.

In your case, the next hop has been deleted without removing the route, so it's most certainly a bug in the Contiki stack.

If you remove a route via the web interface, the end node does not know its route has been deleted so no new route will be created until the previous route lifetime is expired. To force recreation of the route you must trigger a global repair on the RPL page.

**Comment by laurentderu** [comment]
This was solved in cfbc964d6d843774c71ee3539a5ce11a68350fa9
